<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Selecciona un mtodo de pagoTarjeta d_e12129</name>
   <tag></tag>
   <elementGuidId>3a3118f4-0151-4b57-9b6d-574f36f5fcc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='metodoPago']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#metodoPago</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Método de Pago&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9f1e12b6-605e-4107-9503-bea804ed7b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>metodoPago</value>
      <webElementGuid>b3e0b50b-11b6-4288-9c1d-091565911edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>metodoPago</value>
      <webElementGuid>0f39cf9c-2496-4ef9-b31e-1a07c9f55d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>afb629b1-5f52-4b4e-95f2-beac278ef807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selecciona un método de pagoTarjeta de Crédito Tarjeta de Débito Transferencia Bancaria Pago en Efectivo </value>
      <webElementGuid>9d796b91-33cc-4e76-bb8a-a320fa826ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;metodoPago&quot;)</value>
      <webElementGuid>022ce52d-5f8d-4d7e-8797-c3b3b020c26d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='metodoPago']</value>
      <webElementGuid>a7daaef7-6464-445a-8da2-123aadf8823e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Método de Pago'])[1]/following::select[1]</value>
      <webElementGuid>3cda8a97-4e65-4528-a62a-a95a8bbfa67f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciudad'])[1]/following::select[1]</value>
      <webElementGuid>1ebddc03-a7ce-4bd1-b71e-c96b5f555413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Por favor, selecciona un método de pago.'])[1]/preceding::select[1]</value>
      <webElementGuid>848efbc1-76f6-4555-914d-5224b724ee75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Realizar Pago'])[1]/preceding::select[1]</value>
      <webElementGuid>2e88ba1e-4bf7-410f-bd91-5637ffaedfde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>3c2d77fb-e4a4-4239-868b-40ad7476c08a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'metodoPago' and (text() = 'Selecciona un método de pagoTarjeta de Crédito Tarjeta de Débito Transferencia Bancaria Pago en Efectivo ' or . = 'Selecciona un método de pagoTarjeta de Crédito Tarjeta de Débito Transferencia Bancaria Pago en Efectivo ')]</value>
      <webElementGuid>f9f01989-ca75-4267-8288-a04c225b0ef3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
