<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_8</name>
   <tag></tag>
   <elementGuidId>3c1b6519-f5a4-44c0-8f96-a3d9ba0092bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='producto']/div[2]/nav/ul/li[9]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;8&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>49b16410-ebc4-4174-bc7e-f5ce0153930a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-link clickable</value>
      <webElementGuid>cb98b5aa-b54c-407b-a65c-3fd050e343a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>b878f0c0-9eb4-41dc-a139-6c531a02ee79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;producto&quot;)/div[@class=&quot;mt-4 d-flex justify-content-center&quot;]/nav[1]/ul[@class=&quot;pagination&quot;]/li[@class=&quot;page-item&quot;]/a[@class=&quot;page-link clickable&quot;]</value>
      <webElementGuid>bf3ef944-26ff-4b6e-9985-b65087ee3dda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='producto']/div[2]/nav/ul/li[9]/a</value>
      <webElementGuid>561cdf76-8a35-4a89-8408-8c9b329da614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'8')]</value>
      <webElementGuid>394852c9-c408-445e-b816-0ee5012bbe0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anterior'])[1]/following::a[8]</value>
      <webElementGuid>7d9ff252-8f37-4901-8afa-1781a1788337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$5.99'])[4]/following::a[9]</value>
      <webElementGuid>a76b611a-95c8-4e70-bab2-e697f3a3e171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Siguiente'])[1]/preceding::a[3]</value>
      <webElementGuid>d24397ee-3f21-41ef-9254-1f55ba7244ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='8']/parent::*</value>
      <webElementGuid>58023c44-8734-4b9d-aa30-63e247d8c1b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/a</value>
      <webElementGuid>415c3141-39ca-4f2b-9863-e53314c69133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '8' or . = '8')]</value>
      <webElementGuid>f47968b6-4da6-49b2-942d-30e6bdfd13e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
