<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Eliminar_1</name>
   <tag></tag>
   <elementGuidId>640c32bb-4fd0-4164-a12d-bbd2c7133149</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[36]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(8) > div.card.card-product > div.card-body > div.d-flex.justify-content-between.align-items-center.mt-3 > button.btn.btn-danger.btn-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(8) > .card > .card-body > .d-flex > button:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4e2a8a42-fef2-4a4c-a185-8ecdc08cc904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cdb267d9-d4a8-4e4f-86fc-9895c7266ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-sm</value>
      <webElementGuid>96cbaf8a-79d8-47fb-96f5-583ec9dbd8d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Eliminar </value>
      <webElementGuid>ff6bd887-83ab-45f4-8bff-a774837ada03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;producto&quot;)/div[@class=&quot;d-flex flex-wrap justify-content-between gap-3 mt-3&quot;]/div[8]/div[@class=&quot;card card-product&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;d-flex justify-content-between align-items-center mt-3&quot;]/button[@class=&quot;btn btn-danger btn-sm&quot;]</value>
      <webElementGuid>1235fea5-7959-446d-8d92-866fe27c3568</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[36]</value>
      <webElementGuid>daa94afb-d276-4675-86f8-4fe2d73ac9c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='producto']/div/div[8]/div/div/div[4]/button[2]</value>
      <webElementGuid>5926b828-eab7-4108-b05b-5a4a9bc01541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar'])[17]/following::button[1]</value>
      <webElementGuid>bafcb3a3-5298-4d42-baac-0982ee9af36e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$5.99'])[1]/following::button[2]</value>
      <webElementGuid>749d76a5-f2d3-4069-b9c8-2a7aa84f106d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pastel de Zanahoria'])[1]/preceding::button[1]</value>
      <webElementGuid>d091bb3e-8762-4f15-8889-ac90948aceed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Galletas'])[5]/preceding::button[1]</value>
      <webElementGuid>4218a7e2-a7c3-4d56-a042-39899ae940ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[4]/button[2]</value>
      <webElementGuid>a700bd77-f80d-4b0d-9a70-69c8327eed66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Eliminar ' or . = ' Eliminar ')]</value>
      <webElementGuid>3c0733b8-28bd-4529-a790-4482bb984dbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
