<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Selecciona una categoraPastelesCupca_d69aff</name>
   <tag></tag>
   <elementGuidId>33abdc1f-475b-4b7c-a2b7-53fcd54bcd32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='categoria']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#categoria</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Categoría&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>17257285-bdb9-4bc6-8ce2-c6588b4ffb4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>categoria</value>
      <webElementGuid>79501063-95e4-49c3-8b35-d56b5bf4aedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>categoria</value>
      <webElementGuid>586dbbcd-fe48-48f3-8d4c-6d2da230e32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>e3fb138c-a32d-45fa-aa0c-6881fd4cba28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selecciona una categoríaPastelesCupcakesGalletasTartasCategoria nueva 2Pasteles FritosMuffins x4tortas</value>
      <webElementGuid>d6a80c59-83c2-4b70-9fca-7e84382ac9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categoria&quot;)</value>
      <webElementGuid>ab9f5c54-9d40-42c7-b4d0-44a039075111</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='categoria']</value>
      <webElementGuid>c0ba3e92-4459-4894-a312-36a5c0ddc73b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseTwo']/div/admin-producto/admin-common-app-producto/div/form/div[6]/select</value>
      <webElementGuid>70c535a2-b2da-415a-89bd-75ed01e0ccc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categoría'])[1]/following::select[1]</value>
      <webElementGuid>74cc0430-7b86-4acc-afab-6caf67d2f086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stock'])[1]/following::select[1]</value>
      <webElementGuid>1a1f6b14-159a-45c3-a4a8-93def79c3a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar'])[2]/preceding::select[1]</value>
      <webElementGuid>c2f2ff67-6388-44dd-8c74-814c5e9907c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pastel de Chocolate'])[1]/preceding::select[1]</value>
      <webElementGuid>0fb4bbe3-8b20-4f4c-ba65-f1f8c2ec1016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>5d78ade2-9932-4b6f-aa23-9b53a1f5da5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'categoria' and (text() = 'Selecciona una categoríaPastelesCupcakesGalletasTartasCategoria nueva 2Pasteles FritosMuffins x4tortas' or . = 'Selecciona una categoríaPastelesCupcakesGalletasTartasCategoria nueva 2Pasteles FritosMuffins x4tortas')]</value>
      <webElementGuid>d9879ee9-2947-4e6c-8ac7-8fcdd519e7ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
