<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>b93f8b03-30b7-4e86-bd75-a43ae56b9a91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='validationTooltipUsernamePrepend']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#validationTooltipUsernamePrepend</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;@&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c78e1439-75c2-4e58-8763-aa158ae23f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>validationTooltipUsernamePrepend</value>
      <webElementGuid>f38cdbed-2ea6-4e29-ba40-7c36fbadf2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-group-text</value>
      <webElementGuid>4c2a143d-f65a-4465-aa3c-cafb2020cee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>@</value>
      <webElementGuid>7b2ed50c-fd29-4e1c-8937-1cac52172948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;validationTooltipUsernamePrepend&quot;)</value>
      <webElementGuid>86b136dd-9b31-4bd4-9248-ea0d7e5ee172</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='validationTooltipUsernamePrepend']</value>
      <webElementGuid>c58f9c1d-8966-4a35-bef4-42d65dc33321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INICIAR SESIÓN'])[1]/following::span[1]</value>
      <webElementGuid>ad20de74-49ba-4872-8434-1c84efaff4b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Por favor, completar.'])[1]/preceding::span[1]</value>
      <webElementGuid>c461b84d-81e7-4803-8cbd-97afa19294a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Constraseña'])[1]/preceding::span[1]</value>
      <webElementGuid>9a156908-676b-4ae1-b48c-cd4d64e70703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='@']/parent::*</value>
      <webElementGuid>633debe8-c38f-4992-93d5-115a39204aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>306db10a-16ad-4efe-a4f2-f8ac9a18fc81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'validationTooltipUsernamePrepend' and (text() = '@' or . = '@')]</value>
      <webElementGuid>f36c534d-9f1c-4793-bdeb-3ba5fa57ba81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
