<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>use</name>
   <tag></tag>
   <elementGuidId>69915a87-b687-4762-a974-98ef78ddba85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>use</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;2 unread messages&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>use</value>
      <webElementGuid>9ed6dbaf-30b0-4ea9-b3ff-6e675027843a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xlink:href</name>
      <type>Main</type>
      <value>#cart</value>
      <webElementGuid>28e2e75f-a766-4d58-8f3e-e26e2bf76bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-tienda[1]/html[1]/body[1]/main[@class=&quot;barra_navegacion&quot;]/app-navbar[1]/nav[@class=&quot;navbar navbar-expand-xxl navbar-light bg-light&quot;]/div[@class=&quot;container-fluid&quot;]/ul[@class=&quot;navbar-nav&quot;]/li[@class=&quot;d-flex&quot;]/a[@class=&quot;nav-link&quot;]/svg[@class=&quot;bi&quot;]/use[1]</value>
      <webElementGuid>7b60f657-5117-41cf-82e1-ed0ed469f90b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
