<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombre_nombre_1</name>
   <tag></tag>
   <elementGuidId>24c36ebd-a2d0-4e88-a80f-b2109ca4f5eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='nombre'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mb-1 > #nombre</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#collapseTwo #nombre</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe65905c-a773-451c-869c-49a1d541b7ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5774c6bd-f22f-441d-8999-0e060af66347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nombre</value>
      <webElementGuid>36d22ad4-a061-4814-857b-31382fe69893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>nombre</value>
      <webElementGuid>80d55c39-8fb0-4052-a297-67890832f4a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>75e88517-9a78-4849-bfae-c24889c051e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapseTwo&quot;)/div[@class=&quot;accordion-body&quot;]/admin-producto[1]/admin-common-app-producto[1]/div[@class=&quot;container mt-5&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;mb-1&quot;]/input[@id=&quot;nombre&quot;]</value>
      <webElementGuid>1dafe878-d184-4e15-bece-17c3c25a34dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='nombre'])[2]</value>
      <webElementGuid>5012ff77-1df6-405c-bb77-163207d76af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseTwo']/div/admin-producto/admin-common-app-producto/div/form/div/input</value>
      <webElementGuid>d5f04257-27de-4721-b628-d24678fb5c04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//admin-common-app-producto/div/form/div/input</value>
      <webElementGuid>7350f034-40bc-45dc-afda-1f632935bb8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nombre']</value>
      <webElementGuid>396b83d5-8f03-4266-8db6-0ef991ec8346</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
