<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Descripcin_descripcion_1</name>
   <tag></tag>
   <elementGuidId>439f1918-dabf-4f92-8f2f-a71a414b854e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@id='descripcion'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mb-1 > #descripcion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#collapseTwo #descripcion</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f2dc02f4-7362-472d-9a7c-cf7c8c3e6927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>descripcion</value>
      <webElementGuid>a5222ecf-c285-4877-85ee-74116e269c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>descripcion</value>
      <webElementGuid>1e85b046-eb86-498f-9d66-0f4a76b40ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>1b8d96e4-d423-420a-8119-ba0e94eeb262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapseTwo&quot;)/div[@class=&quot;accordion-body&quot;]/admin-producto[1]/admin-common-app-producto[1]/div[@class=&quot;container mt-5&quot;]/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;mb-1&quot;]/textarea[@id=&quot;descripcion&quot;]</value>
      <webElementGuid>0283a360-5a7b-4034-9577-d1af536eb312</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@id='descripcion'])[2]</value>
      <webElementGuid>46849b57-afce-400e-8685-5328ef1ca589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseTwo']/div/admin-producto/admin-common-app-producto/div/form/div[2]/textarea</value>
      <webElementGuid>5d6f65ac-e92c-4a91-aca9-bb654cbd9993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//admin-common-app-producto/div/form/div[2]/textarea</value>
      <webElementGuid>15c7c0a7-c712-4ea0-8da6-0676ab9084dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'descripcion']</value>
      <webElementGuid>45cc10b5-0f88-43da-9c0e-c94ee3448246</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
