<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Misin</name>
   <tag></tag>
   <elementGuidId>870cfd4a-bf54-4aba-b60f-54f8acbdf675</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Nuestra Historia'])[1]/following::h2[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Misión&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>a3a8c6ce-d65e-49f6-9fd6-e125df2a9223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-4 color-title</value>
      <webElementGuid>6f233133-5c8b-4f02-b027-08ed77fc8432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Misión</value>
      <webElementGuid>7d7eee32-e138-4f0a-8af3-28359a7e7071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-quienes-somos[1]/div[@class=&quot;container text-center p-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;container py-5&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-md-10 text-start&quot;]/h2[@class=&quot;mb-4 color-title&quot;]</value>
      <webElementGuid>3bbec5a7-9da5-460b-89bd-c573267b7b29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nuestra Historia'])[1]/following::h2[1]</value>
      <webElementGuid>6069dc93-edfd-4a63-8a00-842675caf67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visión'])[1]/preceding::h2[1]</value>
      <webElementGuid>9414627d-f465-4b88-91e0-7d03a593ddf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Objetivo'])[1]/preceding::h2[2]</value>
      <webElementGuid>4577b39d-57e1-41f3-8d7f-7602252f2eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Misión']/parent::*</value>
      <webElementGuid>2cad5fc8-af19-4ad3-bfe2-323bd5173200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/div/h2</value>
      <webElementGuid>57721c72-5f1d-4698-b88d-ba0647e138cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Misión' or . = 'Misión')]</value>
      <webElementGuid>42d1bfdc-7123-405f-8fa3-8c0a9f1f120a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
