<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Objetivo</name>
   <tag></tag>
   <elementGuidId>db7c5b52-de50-4f8f-a017-aac15137847f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Visión'])[1]/following::h2[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.mb-4.text-start.color-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Objetivo&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>61884787-6ac5-45a8-a1ad-54977b67dbe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-4 text-start color-title</value>
      <webElementGuid>c3cbd962-c7a8-45eb-accd-2f5305d9ad3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Objetivo</value>
      <webElementGuid>598a2964-ed58-4147-b5c5-74ef4696be67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-quienes-somos[1]/div[@class=&quot;container text-center p-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;container py-5&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-md-10 text-start&quot;]/h2[@class=&quot;mb-4 text-start color-title&quot;]</value>
      <webElementGuid>97d41d14-4c73-495e-97d0-e369f56adbe3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visión'])[1]/following::h2[1]</value>
      <webElementGuid>2e7abfc5-e9db-4055-9ba7-f0ad2d5132c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Misión'])[1]/following::h2[2]</value>
      <webElementGuid>e7e7cb9b-073d-4e36-971d-1af2ad7053ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advertencia'])[1]/preceding::h2[1]</value>
      <webElementGuid>f714b523-fa64-48eb-b0a4-499bdbd606a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No hay suficiente stock para realizar la venta.'])[1]/preceding::h2[1]</value>
      <webElementGuid>ce576624-92ff-4d05-a296-03e756264454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Objetivo']/parent::*</value>
      <webElementGuid>38c32c0e-7258-4962-8e08-263d2a3f08eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2[3]</value>
      <webElementGuid>6a541fcb-f213-4d2c-95fd-9ffd6dc698a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Objetivo' or . = 'Objetivo')]</value>
      <webElementGuid>116705c2-7668-43e1-97b7-97b624ab10ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
