<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Selecciona una categoraPastelesCupca_4679d6 (1)</name>
   <tag></tag>
   <elementGuidId>eabe9582-c182-4ba9-a097-2ebaadb3add1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='categoria']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#categoria</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Categoría&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5de5184b-d713-4c2d-b210-4112f9485817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>categoria</value>
      <webElementGuid>ff59e90a-187e-4412-ba7a-60a72760d01f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>categoria</value>
      <webElementGuid>3d2912cd-9758-411f-af1a-e77a58a0cea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>e66471ae-7a11-461a-b46e-fe99a9b60c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selecciona una categoríaPastelesCupcakesGalletasTartasCategoria nueva 2Pasteles Fritostortastorta de chocolatemuffins x4tortas mexicanastortas mexicanastortas mexicanastortas mexicanas</value>
      <webElementGuid>7159d228-7dcb-4bd7-815c-a095401fd667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categoria&quot;)</value>
      <webElementGuid>cd4e271a-b808-4242-94c6-5e265738b306</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='categoria']</value>
      <webElementGuid>dcf94dd1-042e-4f90-aacd-070d12d50ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseTwo']/div/admin-producto/admin-common-app-producto/div/form/div[6]/select</value>
      <webElementGuid>9f710b30-4ba4-4198-9458-ddd3266b070d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categoría'])[1]/following::select[1]</value>
      <webElementGuid>3024440e-8f6c-40e7-8cfb-36bebd3ee561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stock'])[1]/following::select[1]</value>
      <webElementGuid>642081ba-8171-4861-81f3-06add1639957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar'])[2]/preceding::select[1]</value>
      <webElementGuid>83ddc240-3e46-4ad9-8059-06103d96fe1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pastel de Chocolate'])[1]/preceding::select[1]</value>
      <webElementGuid>c60b80f4-f085-4eb4-b5d6-bbf91254df82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a7f15fc6-f5a4-4857-be92-bc9c667904ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'categoria' and (text() = 'Selecciona una categoríaPastelesCupcakesGalletasTartasCategoria nueva 2Pasteles Fritostortastorta de chocolatemuffins x4tortas mexicanastortas mexicanastortas mexicanastortas mexicanas' or . = 'Selecciona una categoríaPastelesCupcakesGalletasTartasCategoria nueva 2Pasteles Fritostortastorta de chocolatemuffins x4tortas mexicanastortas mexicanastortas mexicanastortas mexicanas')]</value>
      <webElementGuid>b6ee82db-8466-4c7c-afc2-13c57ce55fbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
