<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Selecciona una categoraPastelesCupca_1d192f</name>
   <tag></tag>
   <elementGuidId>6f205b9d-16d1-46b5-9712-08c3bb212ac8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='categoria']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#categoria</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Categoría&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>184b325c-9c3c-4414-8242-cfd0cfdd2000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>categoria</value>
      <webElementGuid>b1cd87ae-ad2f-43d6-a84d-ddfe7d62c377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>categoria</value>
      <webElementGuid>b0d398c1-f890-49be-b73b-a6c2e8cadf65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>9403db79-71e0-4776-b9b1-8495df8491bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selecciona una categoríaPastelesCupcakesGalletasTartasCategoria nueva 2Pasteles Fritostortastorta de chocolatemuffins x4tortas mexicanastortas mexicanastortas mexicanastortas mexicanastortas mexicanastortas mexicanastortas mexicanas</value>
      <webElementGuid>99713ad9-fd8c-4224-af45-7d2fe39aec3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categoria&quot;)</value>
      <webElementGuid>dc2e0e9e-897e-45f9-a308-3d8a1fbeb6f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='categoria']</value>
      <webElementGuid>723fe778-d247-45d2-b6c8-3e9c0f21bc7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseTwo']/div/admin-producto/admin-common-app-producto/div/form/div[6]/select</value>
      <webElementGuid>8362a34a-9eff-4e0f-9a96-37b6478d05cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categoría'])[1]/following::select[1]</value>
      <webElementGuid>7d966266-7e15-484e-9977-b309976a76f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stock'])[1]/following::select[1]</value>
      <webElementGuid>ebc63808-1e8d-4175-b2fb-8805fd7aad99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar'])[2]/preceding::select[1]</value>
      <webElementGuid>3d25be4f-de8f-42b0-b20f-a55ab88b84ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pastel de Chocolate'])[1]/preceding::select[1]</value>
      <webElementGuid>7420a89b-3518-42c2-a867-75a3c3cd53fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>63dfc628-3181-4ba5-87bb-cf6f2e46c7c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'categoria' and (text() = 'Selecciona una categoríaPastelesCupcakesGalletasTartasCategoria nueva 2Pasteles Fritostortastorta de chocolatemuffins x4tortas mexicanastortas mexicanastortas mexicanastortas mexicanastortas mexicanastortas mexicanastortas mexicanas' or . = 'Selecciona una categoríaPastelesCupcakesGalletasTartasCategoria nueva 2Pasteles Fritostortastorta de chocolatemuffins x4tortas mexicanastortas mexicanastortas mexicanastortas mexicanastortas mexicanastortas mexicanastortas mexicanas')]</value>
      <webElementGuid>43bb2c5e-5ffe-4f68-b7d6-4b55ddb6091d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Galletas de Avena y Miel'])[1]/preceding::select[1]</value>
      <webElementGuid>70dc900e-8f36-4614-98a5-227c28e808a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'categoria' and (text() = 'Selecciona una categoríaPastelesCupcakesGalletasTartasCategoria nueva 2Pasteles Fritostortastorta de chocolatemuffins x4tortas mexicanastortas mexicanastortas mexicanastortas mexicanastortas mexicanastortas mexicanas' or . = 'Selecciona una categoríaPastelesCupcakesGalletasTartasCategoria nueva 2Pasteles Fritostortastorta de chocolatemuffins x4tortas mexicanastortas mexicanastortas mexicanastortas mexicanastortas mexicanastortas mexicanas')]</value>
      <webElementGuid>6706f56f-88fc-4973-a0ea-11ed0b8eeca7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
