<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Selecciona una categoraPastelesCupca_4679d6</name>
   <tag></tag>
   <elementGuidId>9720e12f-182c-46d0-92a7-43ffdb8dd1de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='categoria']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#categoria</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Categoría&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e2f41560-4e2e-4e05-8081-78546c049fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>categoria</value>
      <webElementGuid>1d842392-477a-4fac-9c15-a92a085fa72a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>categoria</value>
      <webElementGuid>ae2c01ab-2dc7-47ff-aacd-026f8b08c135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>e0dfe34a-e256-4e2d-ab6f-8161cb5d9df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selecciona una categoríaPastelesCupcakesGalletasTartasCategoria nueva 2Pasteles Fritostortastorta de chocolatemuffins x4tortas mexicanastortas mexicanastortas mexicanastortas mexicanas</value>
      <webElementGuid>20d6a57e-38ea-4b5d-a35a-af2f2d83a119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categoria&quot;)</value>
      <webElementGuid>bfe6035c-3b60-4567-9796-55171e4e847b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='categoria']</value>
      <webElementGuid>ebabb0de-9025-422c-9807-9c05a01eced5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseTwo']/div/admin-producto/admin-common-app-producto/div/form/div[6]/select</value>
      <webElementGuid>cdb73b2e-78aa-49e6-b101-ce30e9120a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categoría'])[1]/following::select[1]</value>
      <webElementGuid>c20e5d2a-de75-45fd-b790-335491143816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stock'])[1]/following::select[1]</value>
      <webElementGuid>d18ec7ac-ea4e-4247-8161-426bc9249613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar'])[2]/preceding::select[1]</value>
      <webElementGuid>db2844a9-2006-4372-b656-fb4d3ba117e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pastel de Chocolate'])[1]/preceding::select[1]</value>
      <webElementGuid>c2cf3b64-cb21-4b7d-a2f9-e0c4c2e77cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>464186ee-2684-4d85-868f-76c1995b2260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'categoria' and (text() = 'Selecciona una categoríaPastelesCupcakesGalletasTartasCategoria nueva 2Pasteles Fritostortastorta de chocolatemuffins x4tortas mexicanastortas mexicanastortas mexicanastortas mexicanas' or . = 'Selecciona una categoríaPastelesCupcakesGalletasTartasCategoria nueva 2Pasteles Fritostortastorta de chocolatemuffins x4tortas mexicanastortas mexicanastortas mexicanastortas mexicanas')]</value>
      <webElementGuid>df13fbc6-7035-4427-aebb-fad037c76259</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
